// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MusicApp",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "MusicApp",
            targets: ["AppModule"],
            bundleIdentifier: "br.ufpe.cin.academy.mvpc.MusicApp",
            teamIdentifier: "9569K2P89M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .entertainment
        )
    ],
    dependencies: [
        .package(url: "https://github.com/davdroman/swiftui-navigation-transitions.git", "0.9.0"..<"1.0.0"),
        .package(url: "https://github.com/CodeSlicing/pure-swift-ui", "3.0.0"..<"4.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "NavigationTransitions", package: "swiftui-navigation-transitions"),
                .product(name: "PureSwiftUI", package: "pure-swift-ui")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)